
services:
  - type: web
    name: tiberbu-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn tiberbu_appointmentscheduling.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiberbu-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: FRONTEND_URL
        sync: false

databases:
  - name: tiberbu-db
    plan: free

services:
  - type: web
    name: tiberbu-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate

