# Generated by Django 4.2.20 on 2025-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiberbuappointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_times',
            field=models.JSONField(default=list),
        ),
    ]
