# Generated by Django 4.2.20 on 2026-10-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiberbuappointments', '0002_alter_doctor_available_times'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('doctor', 'appointment_date'), name='unique_active_slot'),
        ),
    ]
