# Generated by Django 4.2.20 on 2026-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiberbuappointments', '0003_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
